/*
 * This file was automatically generated by EvoSuite
 * Sat Mar 12 20:41:15 GMT 2016
 */

package atm.physical;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import atm.ATM;
import atm.physical.CardReader;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class CardReader_ESTest extends CardReader_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CardReader cardReader0 = new CardReader((ATM) null);
      cardReader0.readCard();
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      CardReader cardReader0 = new CardReader((ATM) null);
      cardReader0.ejectCard();
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      CardReader cardReader0 = new CardReader((ATM) null);
      cardReader0.retainCard();
  }
}
