/*
 * This file was automatically generated by EvoSuite
 * Sat Mar 12 18:21:27 GMT 2016
 */

package atm.transaction;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import atm.ATM;
import atm.Session;
import atm.transaction.Deposit;
import banking.Card;
import java.net.Inet4Address;
import java.net.InetAddress;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.net.MockInetAddress;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Deposit_ESTest extends Deposit_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Inet4Address inet4Address0 = (Inet4Address)MockInetAddress.getByName("$40");
      ATM aTM0 = new ATM(0, "$40", "$40", (InetAddress) inet4Address0);
      Card card0 = new Card(0);
      Deposit deposit0 = new Deposit(aTM0, (Session) null, card0, 0);
      // Undeclared exception!
      try { 
        deposit0.getSpecificsFromCustomer();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("atm.physical.CustomerConsole", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Session session0 = new Session((ATM) null);
      Deposit deposit0 = new Deposit((ATM) null, session0, (Card) null, 0);
      // Undeclared exception!
      try { 
        deposit0.completeTransaction();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("atm.transaction.Deposit", e);
      }
  }
}
