/*
 * This file was automatically generated by EvoSuite
 * Sat Mar 12 19:33:12 GMT 2016
 */

package atm.transaction;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import atm.ATM;
import atm.Session;
import atm.transaction.Transfer;
import banking.Card;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Transfer_ESTest extends Transfer_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Transfer transfer0 = new Transfer((ATM) null, (Session) null, (Card) null, 0);
      // Undeclared exception!
      try { 
        transfer0.getSpecificsFromCustomer();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("atm.transaction.Transfer", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Transfer transfer0 = new Transfer((ATM) null, (Session) null, (Card) null, 2599);
      // Undeclared exception!
      try { 
        transfer0.completeTransaction();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("banking.Receipt", e);
      }
  }
}
