/*
 * This file was automatically generated by EvoSuite
 * Sat Mar 12 17:45:45 GMT 2016
 */

package atm.transaction;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import atm.ATM;
import atm.Session;
import atm.transaction.Deposit;
import atm.transaction.Inquiry;
import atm.transaction.Transaction;
import atm.transaction.Transfer;
import atm.transaction.Withdrawal;
import banking.Card;
import java.net.Inet4Address;
import java.net.InetAddress;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.net.MockInetAddress;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Transaction_ESTest extends Transaction_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Inet4Address inet4Address0 = (Inet4Address)MockInetAddress.getLocalHost();
      ATM aTM0 = new ATM(3424, "*_?nlHJ9B&", "", (InetAddress) inet4Address0);
      Session session0 = new Session(aTM0);
      Card card0 = new Card((-3552));
      Withdrawal withdrawal0 = new Withdrawal(aTM0, session0, card0, (-1401));
      Deposit deposit0 = new Deposit(aTM0, session0, card0, 3);
      // Undeclared exception!
      try { 
        deposit0.performTransaction();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("atm.physical.CustomerConsole", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Inet4Address inet4Address0 = (Inet4Address)MockInetAddress.getLoopbackAddress();
      ATM aTM0 = new ATM(883, "Last transaction was cancelled", "Last transaction was cancelled", (InetAddress) inet4Address0);
      Session session0 = new Session(aTM0);
      Inquiry inquiry0 = new Inquiry(aTM0, session0, (Card) null, 883);
      assertEquals(1, inquiry0.getSerialNumber());
      
      inquiry0.serialNumber = 0;
      int int0 = inquiry0.getSerialNumber();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Inet4Address inet4Address0 = (Inet4Address)MockInetAddress.anyLocalAddress();
      Card card0 = new Card(6);
      ATM aTM0 = new ATM(6, "^<]!`", "", (InetAddress) inet4Address0);
      Session session0 = new Session(aTM0);
      Transfer transfer0 = new Transfer(aTM0, session0, card0, 313);
      transfer0.serialNumber = (-899);
      int int0 = transfer0.getSerialNumber();
      assertEquals((-899), int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ATM aTM0 = new ATM(0, "D7U%a2twW", "", (InetAddress) null);
      Session session0 = new Session(aTM0);
      Card card0 = new Card(0);
      Inquiry inquiry0 = new Inquiry(aTM0, session0, card0, 0);
      inquiry0.completeTransaction();
      assertEquals(1, inquiry0.getSerialNumber());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Inet4Address inet4Address0 = (Inet4Address)MockInetAddress.getLoopbackAddress();
      ATM aTM0 = new ATM(0, "flbyPN]]&", "l", (InetAddress) inet4Address0);
      Session session0 = new Session(aTM0);
      Card card0 = new Card(0);
      // Undeclared exception!
      try { 
        Transaction.makeTransaction(aTM0, session0, card0, 0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("atm.physical.CustomerConsole", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Inet4Address inet4Address0 = (Inet4Address)MockInetAddress.getLoopbackAddress();
      ATM aTM0 = new ATM(883, "Last transaction was cancelled", "Last transaction was cancelled", (InetAddress) inet4Address0);
      Session session0 = new Session(aTM0);
      Inquiry inquiry0 = new Inquiry(aTM0, session0, (Card) null, 883);
      // Undeclared exception!
      try { 
        inquiry0.getSpecificsFromCustomer();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("atm.physical.CustomerConsole", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Inet4Address inet4Address0 = (Inet4Address)MockInetAddress.getLocalHost();
      ATM aTM0 = new ATM(0, "Please enter your PIN\nThen press ENTER", "7f_Lqi~o3_", (InetAddress) inet4Address0);
      Session session0 = new Session(aTM0);
      Card card0 = new Card(0);
      Transfer transfer0 = new Transfer(aTM0, session0, card0, 0);
      // Undeclared exception!
      try { 
        transfer0.completeTransaction();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("atm.transaction.Transfer$1", e);
      }
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Inet4Address inet4Address0 = (Inet4Address)MockInetAddress.getByName("Please choose transaction type");
      ATM aTM0 = new ATM((-24), "Please choose transaction type", "Please choose transaction type", (InetAddress) inet4Address0);
      Session session0 = new Session(aTM0);
      Transfer transfer0 = new Transfer(aTM0, session0, (Card) null, (-24));
      // Undeclared exception!
      try { 
        transfer0.performInvalidPINExtension();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("atm.physical.CustomerConsole", e);
      }
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      Inet4Address inet4Address0 = (Inet4Address)MockInetAddress.anyLocalAddress();
      Card card0 = new Card(6);
      ATM aTM0 = new ATM(6, "^<]!`", "", (InetAddress) inet4Address0);
      Session session0 = new Session(aTM0);
      Transfer transfer0 = new Transfer(aTM0, session0, card0, 313);
      int int0 = transfer0.getSerialNumber();
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      Transaction.CardRetained transaction_CardRetained0 = new Transaction.CardRetained();
  }
}
