/*
 * This file was automatically generated by EvoSuite
 * Sat Mar 12 18:05:32 GMT 2016
 */

package atm.transaction;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import atm.ATM;
import atm.Session;
import atm.transaction.Withdrawal;
import banking.Card;
import java.net.InetAddress;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Withdrawal_ESTest extends Withdrawal_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ATM aTM0 = new ATM(0, "", "", (InetAddress) null);
      Session session0 = new Session(aTM0);
      Card card0 = new Card(0);
      Withdrawal withdrawal0 = new Withdrawal(aTM0, session0, card0, 0);
      // Undeclared exception!
      try { 
        withdrawal0.getSpecificsFromCustomer();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("atm.physical.CustomerConsole", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Card card0 = new Card(2157);
      Withdrawal withdrawal0 = new Withdrawal((ATM) null, (Session) null, card0, 2157);
      // Undeclared exception!
      try { 
        withdrawal0.completeTransaction();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("atm.transaction.Withdrawal", e);
      }
  }
}
