/*
 * This file was automatically generated by EvoSuite
 * Sat Mar 12 20:39:30 GMT 2016
 */

package atm.transaction;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import atm.ATM;
import atm.Session;
import atm.transaction.Withdrawal;
import banking.Card;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Withdrawal_ESTest extends Withdrawal_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Withdrawal withdrawal0 = new Withdrawal((ATM) null, (Session) null, (Card) null, 87);
      // Undeclared exception!
      try { 
        withdrawal0.getSpecificsFromCustomer();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("atm.transaction.Withdrawal", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Withdrawal withdrawal0 = new Withdrawal((ATM) null, (Session) null, (Card) null, (-3095));
      // Undeclared exception!
      try { 
        withdrawal0.completeTransaction();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("atm.transaction.Withdrawal", e);
      }
  }
}
