/*
 * This file was automatically generated by EvoSuite
 * Sat Mar 12 18:16:11 GMT 2016
 */

package atm.physical;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import atm.ATM;
import atm.physical.CardReader;
import java.net.Inet4Address;
import java.net.InetAddress;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.net.MockInetAddress;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class CardReader_ESTest extends CardReader_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Inet4Address inet4Address0 = (Inet4Address)MockInetAddress.getByName("");
      ATM aTM0 = new ATM(1, "", "", (InetAddress) inet4Address0);
      CardReader cardReader0 = new CardReader(aTM0);
      // Undeclared exception!
      try { 
        cardReader0.retainCard();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("atm.physical.CardReader", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      CardReader cardReader0 = new CardReader((ATM) null);
      // Undeclared exception!
      try { 
        cardReader0.readCard();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("atm.physical.CardReader", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Inet4Address inet4Address0 = (Inet4Address)MockInetAddress.getLoopbackAddress();
      ATM aTM0 = new ATM((-1), "Response:  ", "Response:  ", (InetAddress) inet4Address0);
      CardReader cardReader0 = new CardReader(aTM0);
      // Undeclared exception!
      try { 
        cardReader0.ejectCard();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("atm.physical.CardReader", e);
      }
  }
}
