/*
 * This file was automatically generated by EvoSuite
 * Sat Mar 12 18:20:09 GMT 2016
 */

package atm.physical;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import atm.physical.CashDispenser;
import atm.physical.Log;
import banking.Money;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class CashDispenser_ESTest extends CashDispenser_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CashDispenser cashDispenser0 = new CashDispenser((Log) null);
      // Undeclared exception!
      try { 
        cashDispenser0.dispenseCash((Money) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("banking.Money", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      CashDispenser cashDispenser0 = new CashDispenser((Log) null);
      cashDispenser0.setInitialCash((Money) null);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Log log0 = new Log();
      CashDispenser cashDispenser0 = new CashDispenser(log0);
      // Undeclared exception!
      try { 
        cashDispenser0.checkCashOnHand((Money) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("atm.physical.CashDispenser", e);
      }
  }
}
