/*
 * This file was automatically generated by EvoSuite
 * Sat Mar 12 19:27:01 GMT 2016
 */

package atm.physical;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import atm.physical.EnvelopeAcceptor;
import atm.physical.Log;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class EnvelopeAcceptor_ESTest extends EnvelopeAcceptor_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Log log0 = new Log();
      EnvelopeAcceptor envelopeAcceptor0 = new EnvelopeAcceptor(log0);
      // Undeclared exception!
      try { 
        envelopeAcceptor0.acceptEnvelope();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("atm.physical.EnvelopeAcceptor", e);
      }
  }
}
