/*
 * This file was automatically generated by EvoSuite
 * Sat Mar 12 18:19:31 GMT 2016
 */

package atm.transaction;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import atm.ATM;
import atm.Session;
import atm.transaction.Inquiry;
import banking.Card;
import banking.Receipt;
import java.net.InetAddress;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Inquiry_ESTest extends Inquiry_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Session session0 = new Session((ATM) null);
      Card card0 = new Card(0);
      Inquiry inquiry0 = new Inquiry((ATM) null, session0, card0, 0);
      // Undeclared exception!
      try { 
        inquiry0.completeTransaction();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("banking.Receipt", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ATM aTM0 = new ATM(2164, "B;EucNf8DReS/", "B;EucNf8DReS/", (InetAddress) null);
      Session session0 = new Session(aTM0);
      Card card0 = new Card(2164);
      Inquiry inquiry0 = new Inquiry(aTM0, session0, card0, 2164);
      // Undeclared exception!
      try { 
        inquiry0.getSpecificsFromCustomer();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("atm.physical.CustomerConsole", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ATM aTM0 = new ATM(2164, "B;EucNf8DReS/", "B;EucNf8DReS/", (InetAddress) null);
      Session session0 = new Session(aTM0);
      Card card0 = new Card(2164);
      Inquiry inquiry0 = new Inquiry(aTM0, session0, card0, 2164);
      Receipt receipt0 = inquiry0.completeTransaction();
      assertNotNull(receipt0);
  }
}
