/*
 * This file was automatically generated by EvoSuite
 * Sat Mar 12 20:35:22 GMT 2016
 */

package atm;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import atm.ATM;
import java.net.InetAddress;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class ATM_ESTest extends ATM_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      ATM aTM0 = new ATM((-999), "Please insert your card", "Please insert your card", (InetAddress) null);
      aTM0.getPlace();
      assertEquals(-999, aTM0.getID());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      ATM aTM0 = new ATM(100, "", "", (InetAddress) null);
      aTM0.getPlace();
      assertEquals(100, aTM0.getID());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      ATM aTM0 = new ATM(1, "TOTAL BAL: ", "TOTAL BAL: ", (InetAddress) null);
      int int0 = aTM0.getID();
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      ATM aTM0 = new ATM((-1452), "Message:   ", "Message:   ", (InetAddress) null);
      int int0 = aTM0.getID();
      assertEquals((-1452), int0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      ATM aTM0 = new ATM(1, "TOTAL BAL: ", "TOTAL BAL: ", (InetAddress) null);
      aTM0.getBankName();
      assertEquals(1, aTM0.getID());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      ATM aTM0 = new ATM((-1052), "0g1Rujz`uv2", "", (InetAddress) null);
      String string0 = aTM0.getBankName();
      assertEquals(-1052, aTM0.getID());
      assertEquals("", string0);
      assertEquals("0g1Rujz`uv2", aTM0.getPlace());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      ATM aTM0 = new ATM(934, (String) null, "", (InetAddress) null);
      // Undeclared exception!
      try { 
        aTM0.run();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("atm.physical.CustomerConsole", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      ATM aTM0 = new ATM(934, (String) null, "", (InetAddress) null);
      String string0 = aTM0.getPlace();
      assertEquals(934, aTM0.getID());
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      ATM aTM0 = new ATM(1, "TOTAL BAL: ", "TOTAL BAL: ", (InetAddress) null);
      aTM0.getEnvelopeAcceptor();
      assertEquals(1, aTM0.getID());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      ATM aTM0 = new ATM(934, (String) null, "", (InetAddress) null);
      aTM0.cardInserted();
      assertEquals(934, aTM0.getID());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      ATM aTM0 = new ATM((-1), "", "", (InetAddress) null);
      aTM0.getCardReader();
      assertEquals(-1, aTM0.getID());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      ATM aTM0 = new ATM(1, "TOTAL BAL: ", "TOTAL BAL: ", (InetAddress) null);
      aTM0.getNetworkToBank();
      assertEquals(1, aTM0.getID());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      ATM aTM0 = new ATM((-999), "Please insert your card", "Please insert your card", (InetAddress) null);
      aTM0.getLog();
      assertEquals(-999, aTM0.getID());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      ATM aTM0 = new ATM(934, (String) null, "", (InetAddress) null);
      aTM0.switchOn();
      assertEquals(934, aTM0.getID());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      ATM aTM0 = new ATM(934, (String) null, "", (InetAddress) null);
      aTM0.getCashDispenser();
      assertEquals(934, aTM0.getID());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      ATM aTM0 = new ATM((-8), "atm.ATM", "Please insert your card", (InetAddress) null);
      aTM0.getOperatorPanel();
      assertEquals("atm.ATM", aTM0.getPlace());
      assertEquals("Please insert your card", aTM0.getBankName());
      assertEquals(-8, aTM0.getID());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      ATM aTM0 = new ATM(934, (String) null, "", (InetAddress) null);
      aTM0.switchOff();
      assertEquals(934, aTM0.getID());
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      ATM aTM0 = new ATM((-2499), "", (String) null, (InetAddress) null);
      String string0 = aTM0.getBankName();
      assertNull(string0);
      assertEquals(-2499, aTM0.getID());
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      ATM aTM0 = new ATM(0, "", "C", (InetAddress) null);
      int int0 = aTM0.getID();
      assertEquals("C", aTM0.getBankName());
      assertEquals("", aTM0.getPlace());
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      ATM aTM0 = new ATM((-999), "Please insert your card", "Please insert your card", (InetAddress) null);
      aTM0.getCustomerConsole();
      assertEquals(-999, aTM0.getID());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      ATM aTM0 = new ATM(934, (String) null, "", (InetAddress) null);
      aTM0.getReceiptPrinter();
      assertEquals(934, aTM0.getID());
  }
}
