/*
 * This file was automatically generated by EvoSuite
 * Sat Mar 12 19:28:42 GMT 2016
 */

package banking;

import org.junit.Test;
import static org.junit.Assert.*;
import banking.AccountInformation;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class AccountInformation_ESTest extends AccountInformation_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      AccountInformation accountInformation0 = new AccountInformation();
  }
}
