/*
 * This file was automatically generated by EvoSuite
 * Sat Mar 12 18:26:14 GMT 2016
 */

package banking;

import org.junit.Test;
import static org.junit.Assert.*;
import banking.Card;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Card_ESTest extends Card_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Card card0 = new Card(2117);
      int int0 = card0.getNumber();
      assertEquals(2117, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Card card0 = new Card((-2554));
      int int0 = card0.getNumber();
      assertEquals((-2554), int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Card card0 = new Card(0);
      int int0 = card0.getNumber();
      assertEquals(0, int0);
  }
}
