/*
 * This file was automatically generated by EvoSuite
 * Sat Mar 12 18:18:10 GMT 2016
 */

package banking;

import org.junit.Test;
import static org.junit.Assert.*;
import banking.Balances;
import banking.Money;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Balances_ESTest extends Balances_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Balances balances0 = new Balances();
      Money money0 = balances0.getTotal();
      assertNull(money0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Balances balances0 = new Balances();
      balances0.setBalances((Money) null, (Money) null);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Balances balances0 = new Balances();
      Money money0 = balances0.getAvailable();
      assertNull(money0);
  }
}
