/*
 * This file was automatically generated by EvoSuite
 * Sat Mar 12 18:24:46 GMT 2016
 */

package atm.physical;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import atm.physical.Log;
import atm.physical.NetworkToBank;
import banking.Balances;
import banking.Message;
import java.net.Inet4Address;
import java.net.InetAddress;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.net.MockInetAddress;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class NetworkToBank_ESTest extends NetworkToBank_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Log log0 = new Log();
      Inet4Address inet4Address0 = (Inet4Address)MockInetAddress.getLoopbackAddress();
      NetworkToBank networkToBank0 = new NetworkToBank(log0, (InetAddress) inet4Address0);
      Balances balances0 = new Balances();
      // Undeclared exception!
      try { 
        networkToBank0.sendMessage((Message) null, balances0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("atm.physical.Log", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Log log0 = new Log();
      Inet4Address inet4Address0 = (Inet4Address)MockInetAddress.getLoopbackAddress();
      NetworkToBank networkToBank0 = new NetworkToBank(log0, (InetAddress) inet4Address0);
      networkToBank0.closeConnection();
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Log log0 = new Log();
      Inet4Address inet4Address0 = (Inet4Address)MockInetAddress.getLoopbackAddress();
      NetworkToBank networkToBank0 = new NetworkToBank(log0, (InetAddress) inet4Address0);
      networkToBank0.openConnection();
  }
}
