/*
 * This file was automatically generated by EvoSuite
 * Sat Mar 12 17:52:23 GMT 2016
 */

package atm;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import atm.ATM;
import atm.Session;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Session_ESTest extends Session_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Session session0 = new Session((ATM) null);
      // Undeclared exception!
      try { 
        session0.performSession();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("atm.Session", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Session session0 = new Session((ATM) null);
      session0.setPIN((-4187));
  }
}
