/*
 * This file was automatically generated by EvoSuite
 * Sat Mar 12 18:08:50 GMT 2016
 */

package simulation;

import org.junit.Test;
import static org.junit.Assert.*;
import java.awt.GridBagConstraints;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import simulation.GUI;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class GUI_ESTest extends GUI_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      GridBagConstraints gridBagConstraints0 = GUI.makeConstraints(0, (-3994), 0, (-3994), (-3994));
      assertEquals(0, gridBagConstraints0.gridwidth);
      assertEquals(10, gridBagConstraints0.anchor);
      assertEquals((-3994), gridBagConstraints0.gridx);
      assertEquals(0, gridBagConstraints0.gridy);
      assertEquals((-3994), gridBagConstraints0.gridheight);
      assertEquals((-3994), gridBagConstraints0.fill);
      assertEquals(1.0, gridBagConstraints0.weightx, 0.01);
      assertEquals(1.0, gridBagConstraints0.weighty, 0.01);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      GridBagConstraints gridBagConstraints0 = GUI.makeConstraints(5, 5, 638, 638, (-1674));
      assertEquals(1.0, gridBagConstraints0.weightx, 0.01);
      assertEquals(5, gridBagConstraints0.gridx);
      assertEquals(5, gridBagConstraints0.gridy);
      assertEquals(1.0, gridBagConstraints0.weighty, 0.01);
      assertEquals((-1674), gridBagConstraints0.fill);
      assertEquals(10, gridBagConstraints0.anchor);
      assertEquals(638, gridBagConstraints0.gridwidth);
      assertEquals(638, gridBagConstraints0.gridheight);
  }
}
